# Generated by Django 4.1.3 on 2022-11-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blackjack', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='StatModel',
        ),
    ]
