# Generated by Django 4.1.3 on 2022-12-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blackjack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='losses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='win_streak',
            field=models.IntegerField(null=True),
        ),
    ]
